spring:
  # --- 로컬 DB (Docker) 설정 ---
  datasource:
    url: jdbc:mysql://localhost:3306/point_service_db
    username: root
    password: root4321 # 로컬 DB 비밀번호 (Git에 올라가도 비교적 안전)
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        # "health"와 "prometheus" 엔드포인트를 외부에서 접근할 수 있도록 허용합니다.
        include: health, prometheus
  endpoint:
    health:
      show-details: always # health 엔드포인트에서 상세 정보를 볼 수 있도록 설정
  metrics:
    tags:
      # 모든 메트릭에 'application'이라는 이름표를 붙여서, 나중에 Grafana에서 구분하기 쉽게 만듭니다.
      application: my-coupon-service