name: CI-CD with Docker to Oracle Cloud

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_name_lower: ${{ steps.set_image_name.outputs.repo_lower }}
      image_tag: ${{ steps.set_image_name.outputs.sha_short }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case image name and tag
        id: set_image_name
        run: |
          repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          sha_short=$(echo "${GITHUB_SHA}" | cut -c1-7)

          echo "repo_lower=$repo_lower" >> $GITHUB_OUTPUT
          echo "sha_short=$sha_short" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: ./b2b-point
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true

          tags: ghcr.io/${{ steps.set_image_name.outputs.repo_lower }}:${{ steps.set_image_name.outputs.sha_short }}

  deploy-to-oracle:
    needs: build-and-push-image 
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose.prod.yml to Oracle Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "/home/ubuntu/app"

      - name: Execute deployment script on Oracle Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/ubuntu/app

            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            export GITHUB_REPOSITORY_LOWER=${{ needs.build-and-push-image.outputs.image_name_lower }}
            export IMAGE_TAG=${{ needs.build-and-push-image.outputs.image_tag }}

            docker compose -f docker-compose.prod.yml up -d --remove-orphans --pull always
            docker image prune -af
